//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TurkeyProvincesEntitie3 : DbContext
    {
        public TurkeyProvincesEntitie3()
            : base("name=TurkeyProvincesEntitie3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PlacesToVisit> PlacesToVisits { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RulingParty> RulingParties { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<TransportationService> TransportationServices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<WhatFamou> WhatFamous { get; set; }
    
        public virtual ObjectResult<SP_TownByCity_Result> SP_TownByCity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TownByCity_Result>("SP_TownByCity");
        }
    
        public virtual ObjectResult<SP_VillageByTown_Result> SP_VillageByTown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VillageByTown_Result>("SP_VillageByTown");
        }
    }
}
