//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public int TownID { get; set; }
        public string TownName { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> PlaceToVisitID { get; set; }
        public Nullable<int> WhatFamousID { get; set; }
        public Nullable<int> TransportationServiceID { get; set; }
        public Nullable<int> PartyID { get; set; }
        public string Population { get; set; }
        public byte[] Picture { get; set; }
    }
}
